// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnfycuysxiqpzuodxsgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuZnljdXlzeGlxcHp1b2R4c2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzM0NzEsImV4cCI6MjA3NDMwOTQ3MX0.fGQjNlF9D-VPhRFKd65Kc3QSONpa8FZtS2oMYkDfHkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});